In [2]:
import tensorflow as tf
from timeit import default_timer

n = 1000
iters = 10000
shape = (n, n)
t1 = tf.random.uniform(shape)
t2 = tf.random.uniform(shape)

time0 = default_timer()
res = [tf.reduce_sum(tf.matmul(t1, t2))]
for _ in range(iters):
    t3 = tf.matmul(t1, t2)
    res.append(tf.reduce_sum(t3))
print(res)
time0 = default_timer() - time0
print("{:.2f} ms/iter".format(time0 / iters * 1000))

[<tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=float32, numpy=249834240.0>, <tf.Tensor: shape=(), dtype=fl